services:
  service:
    build: ./service
    container_name: service-api
    ports:
      - "5000:5000"
    volumes:
      - ${WEBAPP_STORAGE_HOME}/uploads:/app/public/uploads
    environment:
      - ATLAS_URI=mongodb://database:27017/KangAgam-DB?replicaSet=rs0
    depends_on:
      database:
        condition: service_healthy

  client:
    build: ./client
    container_name: client-web
    ports:
      - "3000:80"
    depends_on:
      - service

  database:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ${WEBAPP_STORAGE_HOME}/mongodb_data:/data/db
      - ./seed:/docker-entrypoint-initdb.d
      - ./init-mongo.sh:/usr/local/bin/init-mongo.sh
    command: ["bash", "/usr/local/bin/init-mongo.sh"]
    healthcheck:
      test: |
        mongosh --host database --eval "quit(db.isMaster().ismaster ? 0 : 1)"
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s