name: Build and Deploy Node.js App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x' # Atau sesuaikan dengan versi Node.js Anda

      - name: Install dependencies
        run: npm install

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'kangagam'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Pastikan secret ini ada di pengaturan repositori GitHub Anda
          package: .
