# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - kangagam

on:
  push:
    branches:
      - Docker-test
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_c1caa9d92a6749e8aa1b986656d27a8e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_35711754271c4a5291489a8da99721a3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c1caa9d92a6749e8aa1b986656d27a8e }}/kangagam:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'kangagam'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_080a085a0f5640f1a9238b145efeffe3 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c1caa9d92a6749e8aa1b986656d27a8e }}/kangagam:${{ github.sha }}'